release:
  github:
    owner: grassrootseconomics
    name: w3-celo
  draft: true
  footer: |
    **Full Changelog**: [`{{ .PreviousTag }}…{{ .Tag }}`](https://github.com/{{ .Env.GITHUB_REPOSITORY }}/compare/{{ .PreviousTag }}...{{ .Tag }})

changelog:
  sort: asc
  groups:
    - title: Bug Fixes
      regexp: fix
      order: 1
    - title: ''
      regexp: .*
      order: 0

builds:
- skip: true
